// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getUserId.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserId = `-- name: GetUserId :one
SELECT id
FROM users
WHERE name = $1
`

func (q *Queries) GetUserId(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserId, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
