// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markFeedFetched.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const markLastFeedFetched = `-- name: MarkLastFeedFetched :one
UPDATE feeds
SET last_fetched_at = $1::timestamptz,
    updated_at      = $1::timestamptz
WHERE id = $2
    RETURNING id, last_fetched_at, updated_at
`

type MarkLastFeedFetchedParams struct {
	LastFetchedAt time.Time
	ID            uuid.UUID
}

type MarkLastFeedFetchedRow struct {
	ID            uuid.UUID
	LastFetchedAt sql.NullTime
	UpdatedAt     time.Time
}

func (q *Queries) MarkLastFeedFetched(ctx context.Context, arg MarkLastFeedFetchedParams) (MarkLastFeedFetchedRow, error) {
	row := q.db.QueryRowContext(ctx, markLastFeedFetched, arg.LastFetchedAt, arg.ID)
	var i MarkLastFeedFetchedRow
	err := row.Scan(&i.ID, &i.LastFetchedAt, &i.UpdatedAt)
	return i, err
}
