// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queryUrlById.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const queryById = `-- name: QueryById :one
SELECT feeds.name AS feed_name,
       feeds.id,
       users.name AS user_name,
       feeds.url
FROM feeds
INNER JOIN users ON feeds.user_id = users.id
WHERE feeds.url = $1
`

type QueryByIdRow struct {
	FeedName string
	ID       uuid.UUID
	UserName string
	Url      string
}

func (q *Queries) QueryById(ctx context.Context, url string) (QueryByIdRow, error) {
	row := q.db.QueryRowContext(ctx, queryById, url)
	var i QueryByIdRow
	err := row.Scan(
		&i.FeedName,
		&i.ID,
		&i.UserName,
		&i.Url,
	)
	return i, err
}
