// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queryFeedByUrl.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const queryByUrl = `-- name: QueryByUrl :one
SELECT feeds.name AS feed_name,
       feeds.id,
       users.name AS user_name
FROM feeds
INNER JOIN users ON feeds.user_id = users.id
WHERE feeds.url = $1
`

type QueryByUrlRow struct {
	FeedName string
	ID       uuid.UUID
	UserName string
}

func (q *Queries) QueryByUrl(ctx context.Context, url string) (QueryByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, queryByUrl, url)
	var i QueryByUrlRow
	err := row.Scan(&i.FeedName, &i.ID, &i.UserName)
	return i, err
}
