// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: returnFeeds.sql

package database

import (
	"context"
)

const getUserFeeds = `-- name: GetUserFeeds :many
select feeds.name, feeds.url, users.name AS username
FROM feeds
JOIN users ON feeds.user_id = users.id
`

type GetUserFeedsRow struct {
	Name     string
	Url      string
	Username string
}

func (q *Queries) GetUserFeeds(ctx context.Context) ([]GetUserFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedsRow
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
