// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unfollowFeed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE FROM feed_follows
WHERE feed_id = $1 AND user_id = $2
`

type UnfollowFeedParams struct {
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.FeedID, arg.UserID)
	return err
}
